version: '3'

services:
  api-dev:
    build:
      context: .
      dockerfile: dev_image.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # you_local_path/:your_container_path/ which I bind to reflect changes to container
      - ./src:/app/src
    command: npm run dev